### ISSUE TITLE
[Field 'Network.m_lastGameServerInfo' not found]code exception happened after update in October

### ISSUE THREAD

**Issue by chucklu** [ChuckHearthstone/SilverFish#40]
019-10-12 15:24:27.286+08:00 [5] ERROR Triton.Common.LogUtilities.Logger - [Tick] Exception during execution:
System.MissingFieldException: Field 'Network.m_lastGameServerInfo' not found.
   at Triton.Game.Mono.MonoClass.method_5(String string_4)
   at Triton.Game.Mono.MonoClass.method_3[T](String string_4)
   at Triton.Bot.GameEventManager.Tick()
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Tick()
   at Triton.Bot.BotManager.smethod_1(IBot ibot_1)

**Comment by chucklu** [comment]
```C#
// Triton.Game.Mapping.Network
// Token: 0x170027C0 RID: 10176
// (get) Token: 0x06006EF0 RID: 28400 RVA: 0x0005F07D File Offset: 0x0005D27D
public GameServerInfo m_lastGameServerInfo
{
	get
	{
		return base.method_3<GameServerInfo>("m_lastGameServerInfo");
	}
}
```
Old
```C#
// Network
// Token: 0x04003125 RID: 12581
private GameServerInfo m_lastGameServerInfo;

// Network
// Token: 0x06004395 RID: 17301 RVA: 0x00204F7C File Offset: 0x0020337C
public void GotoGameServer(GameServerInfo info, bool reconnecting)
{
	this.m_lastGameServerInfo = info;
```

New
```C#
private Network.NetworkState m_state;
// Network
// Token: 0x06004725 RID: 18213 RVA: 0x00245F30 File Offset: 0x00244330
public void GotoGameServer(GameServerInfo info, bool reconnecting)
{
	this.m_state.LastGameServerInfo = info;
```
a new structure was added
private struct NetworkState

**Comment by chucklu** [comment]
ibot_1.Tick();
```C#
// Triton.Bot.BotManager
// Token: 0x06001132 RID: 4402 RVA: 0x000B5E18 File Offset: 0x000B4018
internal static void smethod_1(IBot ibot_1)
{
	try
	{
		object obj = BotManager.object_0;
		lock (obj)
		{
			if (BotManager.bool_1)
			{
				return;
			}
			BotManager.bool_1 = true;
		}
		BotManager.smethod_3(ibot_1, BotManager.botEvent_2);
		try
		{
			using (TritonHs.AcquireFrame())
			{
				using (TritonHs.Memory.TemporaryCacheState(false))
				{
					TritonHs.Memory.ClearCache();
					ibot_1.Tick();
					TritonHs.smethod_2(false);
				}
			}
		}
		catch (Exception exception)
		{
			BotManager.ilog_0.Error("[Tick] Exception during execution:", exception);
			throw;
		}
		BotManager.smethod_3(ibot_1, BotManager.botEvent_3);
	}
	finally
	{
		object obj = BotManager.object_0;
		lock (obj)
		{
			BotManager.bool_1 = false;
		}
	}
}
```

**Comment by chucklu** [comment]
GameEventManager.Instance.Tick();
```C#
// Triton.Bot.Logic.Bots.DefaultBot.DefaultBot
// Token: 0x0600138F RID: 5007 RVA: 0x000BDF54 File Offset: 0x000BC154
public void Tick()
{
	if (this.coroutine_0.IsFinished)
	{
		DefaultBot.ilog_0.DebugFormat("The bot coroutine has finished in a state of {0}", this.coroutine_0.Status);
		BotManager.Stop();
		return;
	}
	if (!TritonHs.IsClientInUsableState(true))
	{
		BotManager.MsBeforeNextTick += 750;
		this.method_17();
		return;
	}
	if (!this.bool_2 && ChatMgr.Get().FriendListFrame != null)
	{
		DefaultBot.ilog_0.ErrorFormat("[Tick] FriendListFrame != null.", Array.Empty<object>());
		Client.LeftClickAtDialog(BnetBar.Get().m_friendButton.m_OnlineCountText.Transform.Position);
		BotManager.MsBeforeNextTick += 1000;
		this.method_17();
		return;
	}
	bool flag;
	if (TritonHs.HandleDialog(new ShouldAcceptFriendlyChallengeDelegate(this.ShouldAcceptFriendlyChallenge), out flag))
	{
		if (flag)
		{
			BotManager.Stop();
		}
		BotManager.MsBeforeNextTick += 3000;
		this.method_17();
		return;
	}
	GameEventManager.Instance.Tick();
	PluginManager.Tick();
	RoutineManager.Tick();
	try
	{
		this.coroutine_0.Resume();
	}
	catch
	{
		this.method_17();
		throw;
	}
}
```

**Comment by chucklu** [comment]
GameServerInfo lastGameServerInfo = network.m_lastGameServerInfo;
```C#
// Triton.Bot.GameEventManager
// Token: 0x06001166 RID: 4454 RVA: 0x000B69C8 File Offset: 0x000B4BC8
public void Tick()
{
	using (new PerformanceTimer("NewGame", null))
	{
		bool flag = true;
		Network network = Network.Get();
		if (network != null)
		{
			GameServerInfo lastGameServerInfo = network.m_lastGameServerInfo;
			if (Network.IsConnectedToGameServer() && lastGameServerInfo != null && this.int_1 != lastGameServerInfo.GameHandle)
			{
				this.int_1 = lastGameServerInfo.GameHandle;
				this.int_0 = -1;
				this.stopwatch_0.Restart();
				flag = false;
				TritonHs.InvokeEvent(GameEventManager.eventHandler_0, new object[]
				{
					this,
					new NewGameEventArgs(this.int_1)
				});
			}
		}
		if (flag)
		{
			this.stopwatch_0.Reset();
		}
	}
}

```

**Comment by chucklu** [comment]
旧版本
```C#
// Triton.Game.Mapping.Network
// Token: 0x170027C0 RID: 10176
// (get) Token: 0x06006EF0 RID: 28400 RVA: 0x0005F07D File Offset: 0x0005D27D
public GameServerInfo m_lastGameServerInfo
{
	get
	{
		return base.method_3<GameServerInfo>("m_lastGameServerInfo");
	}
}
```

**Comment by chucklu** [comment]
2019-12-21 18:00:27.803+08:00 [7] ERROR Triton.Common.LogUtilities.Logger - [Tick] Exception during execution:
Buddy.Coroutines.CoroutineUnhandledException: Exception was thrown by coroutine ---> System.MissingFieldException: Field 'UberText.m_TextMeshGameObject' not found.
   at Triton.Game.Mono.MonoClass.method_5(String string_4)
   at Triton.Game.Mono.MonoClass.method_3[T](String string_4)
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Struct88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Struct87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Struct60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Buddy.Coroutines.Coroutine.Class66.Struct18.MoveNext()
   --- End of inner exception stack trace ---
   at Buddy.Coroutines.Coroutine.method_2(Boolean bool_2)
   at Buddy.Coroutines.Coroutine.method_0(Boolean bool_2)
   at Buddy.Coroutines.Coroutine.Resume()
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Tick()
   at Triton.Bot.BotManager.smethod_1(IBot ibot_1)

**Comment by chucklu** [comment]
this.coroutine_0.Resume();
```C#
// Triton.Bot.Logic.Bots.DefaultBot.DefaultBot
// Token: 0x0600138F RID: 5007 RVA: 0x000BDF44 File Offset: 0x000BC144
public void Tick()
{
	if (this.coroutine_0.IsFinished)
	{
		DefaultBot.ilog_0.DebugFormat("The bot coroutine has finished in a state of {0}", this.coroutine_0.Status);
		BotManager.Stop();
		return;
	}
	if (!TritonHs.IsClientInUsableState(true))
	{
		BotManager.MsBeforeNextTick += 750;
		this.method_17();
		return;
	}
	if (!this.bool_2 && ChatMgr.Get().FriendListFrame != null)
	{
		DefaultBot.ilog_0.ErrorFormat("[Tick] FriendListFrame != null.", Array.Empty<object>());
		Client.LeftClickAtDialog(BnetBar.Get().m_friendButton.m_OnlineCountText.Transform.Position);
		BotManager.MsBeforeNextTick += 1000;
		this.method_17();
		return;
	}
	bool flag;
	if (TritonHs.HandleDialog(new ShouldAcceptFriendlyChallengeDelegate(this.ShouldAcceptFriendlyChallenge), out flag))
	{
		if (flag)
		{
			BotManager.Stop();
		}
		BotManager.MsBeforeNextTick += 3000;
		this.method_17();
		return;
	}
	GameEventManager.Instance.Tick();
	PluginManager.Tick();
	RoutineManager.Tick();
	try
	{
		this.coroutine_0.Resume();
	}
	catch
	{
		this.method_17();
		throw;
	}
}

```

**Comment by chucklu** [comment]
this.method_0(false);
```C#
// Buddy.Coroutines.Coroutine
// Token: 0x060004C0 RID: 1216 RVA: 0x00093CF4 File Offset: 0x00091EF4
public void Resume()
{
	if (this.IsDisposed)
	{
		throw new ObjectDisposedException(base.GetType().FullName);
	}
	if (this.IsFinished)
	{
		throw new InvalidOperationException("This coroutine has finished execution and cannot be resumed.");
	}
	if (Coroutine.coroutine_0 == this)
	{
		throw new InvalidOperationException("A coroutine cannot resume itself");
	}
	this.method_0(false);
}
```

**Comment by chucklu** [comment]
this.method_2(bool_2);
```C#
// Buddy.Coroutines.Coroutine
// Token: 0x060004C1 RID: 1217 RVA: 0x00093D48 File Offset: 0x00091F48
private void method_0(bool bool_2)
{
	SynchronizationContext synchronizationContext = SynchronizationContext.Current;
	Coroutine coroutine = Coroutine.coroutine_0;
	try
	{
		Coroutine.coroutine_0 = this;
		SynchronizationContext.SetSynchronizationContext(null);
		Action action = this.action_0;
		this.action_0 = null;
		action();
		if (!bool_2)
		{
			this.Ticks++;
		}
		this.method_2(bool_2);
	}
	finally
	{
		Coroutine.coroutine_0 = coroutine;
		SynchronizationContext.SetSynchronizationContext(synchronizationContext);
	}
}
```

**Comment by ghotm** [comment]
Network add:

```
public GameServerInfo GetLastGameServerJoined()
{
	return base.method_14<GameServerInfo>("GetLastGameServerJoined", Array.Empty<object>());
} 
```

Triton.Bot.GameEventManager#Tick

修改`GameServerInfo lastGameServerInfo = network.m_lastGameServerInfo;`为`GameServerInfo lastGameServerInfo = network.GetLastGameServerJoined();`

**Comment by chucklu** [comment]
@ghotm  Thanks.

**Comment by zfz12345** [comment]
> Network add:
> 
> ```
> public GameServerInfo GetLastGameServerJoined()
> {
> 	return base.method_14<GameServerInfo>("GetLastGameServerJoined", Array.Empty<object>());
> } 
> ```
> 
> Triton.Bot.GameEventManager#Tick
> 
> 修改`GameServerInfo lastGameServerInfo = network.m_lastGameServerInfo;`为`GameServerInfo lastGameServerInfo = network.GetLastGameServerJoined();`

Why the last version is unused？How do you know to fix it on this way?
Any ideas？
