### ISSUE TITLE
Field 'EntityDef.m_cardId' not found

### ISSUE THREAD

**Issue by chucklu** [ChuckHearthstone/SilverFish#46]
2020-05-23 17:51:52.748+08:00 [11] ERROR Triton.Common.LogUtilities.Logger - [Tick] Exception during execution:
Buddy.Coroutines.CoroutineUnhandledException: Exception was thrown by coroutine ---> **System.MissingFieldException: Field 'EntityDef.m_cardId' not found.
   at Triton.Game.Mono.MonoClass.method_5(String string_4)
   at Triton.Game.Mapping.EntityBase.get_m_cardId()**
   at HREngine.Bots.Silverfish.getHerostuff() in C:\Users\chuck\Downloads\Hearthbuddy20200521-004\Routines\DefaultRoutine\silverfish_HB.cs:line 489
   at HREngine.Bots.Silverfish.updateEverything(Behavior botbase, Int32 numcal, Boolean& sleepRetry) in C:\Users\chuck\Downloads\Hearthbuddy20200521-004\Routines\DefaultRoutine\silverfish_HB.cs:line 263
   at HREngine.Bots.DefaultRoutine.<OurTurnLogic>d__45.MoveNext() in C:\Users\chuck\Downloads\Hearthbuddy20200521-004\Routines\DefaultRoutine\DefaultRoutine.cs:line 725
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at HREngine.Bots.DefaultRoutine.<Logic>d__39.MoveNext() in C:\Users\chuck\Downloads\Hearthbuddy20200521-004\Routines\DefaultRoutine\DefaultRoutine.cs:line 438
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Struct76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Struct78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Struct71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Struct60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Buddy.Coroutines.Coroutine.Class66.Struct18.MoveNext()
   --- End of inner exception stack trace ---
   at Buddy.Coroutines.Coroutine.method_2(Boolean bool_2)
   at Buddy.Coroutines.Coroutine.method_0(Boolean bool_2)
   at Buddy.Coroutines.Coroutine.Resume()
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Tick()
   at Triton.Bot.BotManager.smethod_1(IBot ibot_1)

**Comment by chucklu** [comment]
The previous property was converted to a method
```C#
// EntityBase
// Token: 0x0600689B RID: 26779 RVA: 0x0022D563 File Offset: 0x0022B763
public string GetCardId()
{
    return this.m_cardId;
}
```

**Comment by chucklu** [comment]
Already have a method 
```C#
// Triton.Game.Mapping.EntityBase
// Token: 0x060030DB RID: 12507 RVA: 0x00027DA5 File Offset: 0x00025FA5
public string GetCardId()
{
    return base.method_13("GetCardId", Array.Empty<object>());
}
```
Fixed by
```C#
public string m_cardId
        {
            get
            {
                return this.GetCardId();
            }
        }
```
