### ISSUE TITLE
AI keep cast the non-targeted spell card "Devolving Missiles" on a target will stuck the game scene.

### ISSUE THREAD

**Issue by ghost** [ChuckHearthstone/SilverFish#54]
The Hearthstone buddy AI keeps trying to cast the card "Devolving Missiles" on a target, which is not a targeted spell.

2021-03-16 16:50:30,832 [28] INFO  Logger (null) - play action
2021-03-16 16:50:30,851 [28] INFO  Logger (null) - play: 魔杖窃贼 (51) target nothing
2021-03-16 16:50:31,625 [28] INFO  Logger (null) - [Pickup] The card was picked up in 127 ms.
2021-03-16 16:50:31,625 [28] INFO  Logger (null) - [UseAt] 1
2021-03-16 16:50:37,320 [28] ERROR Logger (null) - target ...2
2021-03-16 16:50:39,950 [28] INFO  Logger (null) - calculating stuff... 00:50:39.9501
2021-03-16 16:50:40,162 [28] INFO  Logger (null) - calculating ended! 00:50:40.1623
2021-03-16 16:50:40,162 [28] INFO  Logger (null) - end turn
2021-03-16 16:50:41,511 [28] INFO  Logger (null) - [GameplayScene_MAIN_ACTION] Waiting for our turn to fully start/end.
2021-03-16 16:50:41,761 [28] INFO  Logger (null) - [OpponentTurn]
2021-03-16 16:51:26,158 [28] INFO  Logger (null) - [GameplayScene_MAIN_ACTION] Waiting for our turn to fully start/end.
2021-03-16 16:51:27,177 [28] INFO  Logger (null) - [GameplayScene_MAIN_ACTION] Waiting for our turn to fully start/end.
2021-03-16 16:51:27,976 [28] DEBUG Logger (null) - [GameplayScene_MAIN_ACTION_Friendly] Waiting to be in this state longer.
2021-03-16 16:51:29,116 [28] DEBUG Logger (null) - [GameplayScene_MAIN_ACTION_Friendly] Waiting to be in this state longer.
2021-03-16 16:51:30,214 [28] DEBUG Logger (null) - [GameplayScene_MAIN_ACTION_Friendly] Waiting to be in this state longer.
2021-03-16 16:51:32,308 [28] INFO  Logger (null) - calculating stuff... 00:51:32.3083
2021-03-16 16:51:32,499 [30] INFO  Logger (null) - playError:System.NullReferenceException: Object reference not set to an instance of an object.
   at HREngine.Bots.Playfield.minionTransform(Minion m, Card c)
   at ?????????????????????????????????????????.?????????????????????????????????????????(Playfield , Boolean , Minion , Int32 )
   at HREngine.Bots.Playfield.playACard(Handcard hc, Minion target, Int32 position, Int32 choice, Int32 penality)
2021-03-16 16:51:32,501 [30] INFO  Logger (null) - errorID:SCH_235
2021-03-16 16:51:32,501 [30] INFO  Logger (null) - errorID:devolvingmissiles
2021-03-16 16:51:32,501 [30] INFO  Logger (null) - playError:System.NullReferenceException: Object reference not set to an instance of an object.
   at HREngine.Bots.Playfield.minionTransform(Minion m, Card c)
   at ?????????????????????????????????????????.?????????????????????????????????????????(Playfield , Boolean , Minion , Int32 )
   at HREngine.Bots.Playfield.playACard(Handcard hc, Minion target, Int32 position, Int32 choice, Int32 penality)
2021-03-16 16:51:32,502 [30] INFO  Logger (null) - errorID:SCH_235
2021-03-16 16:51:32,502 [30] INFO  Logger (null) - errorID:devolvingmissiles
2021-03-16 16:51:32,502 [30] INFO  Logger (null) - playError:System.NullReferenceException: Object reference not set to an instance of an object.
   at HREngine.Bots.Playfield.minionTransform(Minion m, Card c)
   at ?????????????????????????????????????????.?????????????????????????????????????????(Playfield , Boolean , Minion , Int32 )
   at HREngine.Bots.Playfield.playACard(Handcard hc, Minion target, Int32 position, Int32 choice, Int32 penality)
2021-03-16 16:51:32,503 [30] INFO  Logger (null) - errorID:SCH_235
2021-03-16 16:51:32,503 [30] INFO  Logger (null) - errorID:devolvingmissiles
2021-03-16 16:51:32,504 [30] INFO  Logger (null) - playError:System.NullReferenceException: Object reference not set to an instance of an object.
   at HREngine.Bots.Playfield.minionTransform(Minion m, Card c)
   at ?????????????????????????????????????????.?????????????????????????????????????????(Playfield , Boolean , Minion , Int32 )
   at HREngine.Bots.Playfield.playACard(Handcard hc, Minion target, Int32 position, Int32 choice, Int32 penality)

**Comment by chucklu** [comment]
How did you write the card simulation?

**Comment by lothian173** [comment]
Thank you for reply. Actually the logs captured in the production environment, it is not in the debugging mode.

**Comment by ghost** [comment]
> How did you write the card simulation?

Thank you for reply. Actually it is in the compiled environment with the product, not in the IDE.

**Comment by chucklu** [comment]
> System.NullReferenceException: Object reference not set to an instance of an object.
> at HREngine.Bots.Playfield.minionTransform(Minion m, Card c)
> at ?????????????????????????????????????????.?????????????????????????????????????????(Playfield , Boolean , Minion , Int32 )
> at HREngine.Bots.Playfield.playACard(Handcard hc, Minion target, Int32 position, Int32 choice, Int32 penality)

The above stack trace is not readable, please make sure you open the log file with notepad++.

**Comment by ghost** [comment]
I did open the logs notepad++ again, somehow it is still showing two set of question marks between a dot. This is caused by the Chinese version Hearthstone issue, when Silverfish get the card name it gets the Chinese character, so it is showing as question marks.

From the card name I can guess it could be the card "Jandice.Barov", the logs could be:

System.NullReferenceException: Object reference not set to an instance of an object.
at HREngine.Bots.Playfield.minionTransform(Minion m, Card c)
at Jandice.Barov(Playfield , Boolean , Minion , Int32 )
at HREngine.Bots.Playfield.playACard(Handcard hc, Minion target, Int32 position, Int32 choice, Int32 penality)

**Comment by chucklu** [comment]
@lothian173  The stack trace is not complete, how did you handle the exception? Make sure you handle it correctly
https://stackoverflow.com/questions/730250/is-there-a-difference-between-throw-and-throw-ex

**Comment by ghost** [comment]
The original log text is questions 

> @lothian173 The stack trace is not complete, how did you handle the exception? Make sure you handle it correctly
> https://stackoverflow.com/questions/730250/is-there-a-difference-between-throw-and-throw-ex

Thanks for reply. I think that is the root cause.

May I know if there is any steps for people to start work on this project? For exmaple the recommended IDE, running environment and system requirements, etc.

Thank you.

**Comment by chucklu** [comment]
@lothian173 Actually the AI strategy is supposed to work for both HearthBuddy and HearthRanger.  But how could you get these two bots program is another story. 
To debug the AI, you might check this wiki https://github.com/ChuckHearthstone/SilverFish/wiki/Ai-Test

**Comment by ghost** [comment]
Thank you, I will close this issue.
