### ISSUE TITLE
Field 'CollectionDeckBoxVisual.m_isWild' not found

### ISSUE THREAD

**Issue by chucklu** [ChuckHearthstone/SilverFish#55]
17:33:35.139+08:00 - [CollectionManagerScene_COLLECTION] An exception occurred when calling CacheCustomDecks: System.MissingFieldException: Field 'CollectionDeckBoxVisual.m_isWild' not found.
   at Triton.Game.Mono.MonoClass.method_5(String string_4)
   at Triton.Game.Mono.MonoClass.method_2[T](String string_4)
   at Triton.Bot.Utility.smethod_4()
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Struct57.MoveNext().

**Comment by chucklu** [comment]
The definition of CollectionDeckBoxVisual.m_isWild
```C#
// Triton.Game.Mapping.CollectionDeckBoxVisual
// Token: 0x170013AC RID: 5036
// (get) Token: 0x06003D59 RID: 15705 RVA: 0x00032E64 File Offset: 0x00031064
public bool m_isWild
{
	get
	{
		return base.method_2<bool>("m_isWild");
	}
}
```

**Comment by chucklu** [comment]
New type added 
```C#
// CollectionDeckBoxVisual
// Token: 0x04000A66 RID: 2662
private FormatType m_formatType = FormatType.FT_WILD;

using System;

namespace PegasusShared
{
	// Token: 0x0200016E RID: 366
	public enum FormatType
	{
		// Token: 0x04000808 RID: 2056
		FT_UNKNOWN,
		// Token: 0x04000809 RID: 2057
		FT_WILD,
		// Token: 0x0400080A RID: 2058
		FT_STANDARD,
		// Token: 0x0400080B RID: 2059
		FT_CLASSIC
	}
}
```

**Comment by chucklu** [comment]
2021年04月的版本
狂野模式：除经典模式卡牌外，所有卡牌均可使用
休闲模式：所有卡牌均可使用，与其他休闲玩家对战
```C#
using System;

namespace PegasusShared
{
	// Token: 0x0200016F RID: 367
	public enum BnetGameType
	{
		// Token: 0x0400080D RID: 2061
		BGT_UNKNOWN,
		// Token: 0x0400080E RID: 2062
		BGT_FRIENDS,
		// Token: 0x0400080F RID: 2063
		BGT_RANKED_STANDARD,
		// Token: 0x04000810 RID: 2064
		BGT_ARENA,
		// Token: 0x04000811 RID: 2065
		BGT_VS_AI,
		// Token: 0x04000812 RID: 2066
		BGT_TUTORIAL,
		// Token: 0x04000813 RID: 2067
		BGT_ASYNC,
		// Token: 0x04000814 RID: 2068
		BGT_CASUAL_STANDARD = 10,
		// Token: 0x04000815 RID: 2069
		BGT_TEST1,
		// Token: 0x04000816 RID: 2070
		BGT_TEST2,
		// Token: 0x04000817 RID: 2071
		BGT_TEST3,
		// Token: 0x04000818 RID: 2072
		BGT_TAVERNBRAWL_PVP = 16,
		// Token: 0x04000819 RID: 2073
		BGT_TAVERNBRAWL_1P_VERSUS_AI,
		// Token: 0x0400081A RID: 2074
		BGT_TAVERNBRAWL_2P_COOP,
		// Token: 0x0400081B RID: 2075
		BGT_RANKED_WILD = 30,
		// Token: 0x0400081C RID: 2076
		BGT_CASUAL_WILD,
		// Token: 0x0400081D RID: 2077
		BGT_FSG_BRAWL_VS_FRIEND = 40,
		// Token: 0x0400081E RID: 2078
		BGT_FSG_BRAWL_PVP,
		// Token: 0x0400081F RID: 2079
		BGT_FSG_BRAWL_1P_VERSUS_AI,
		// Token: 0x04000820 RID: 2080
		BGT_FSG_BRAWL_2P_COOP,
		// Token: 0x04000821 RID: 2081
		BGT_RANKED_STANDARD_NEW_PLAYER = 45,
		// Token: 0x04000822 RID: 2082
		BGT_BATTLEGROUNDS = 50,
		// Token: 0x04000823 RID: 2083
		BGT_BATTLEGROUNDS_FRIENDLY,
		// Token: 0x04000824 RID: 2084
		BGT_PVPDR_PAID = 54,
		// Token: 0x04000825 RID: 2085
		BGT_PVPDR,
		// Token: 0x04000826 RID: 2086
		BGT_RESERVED_18_22,
		// Token: 0x04000827 RID: 2087
		BGT_RESERVED_18_23,
		// Token: 0x04000828 RID: 2088
		BGT_RANKED_CLASSIC,
		// Token: 0x04000829 RID: 2089
		BGT_CASUAL_CLASSIC,
		// Token: 0x0400082A RID: 2090
		BGT_LAST
	}
}

```

**Comment by chucklu** [comment]
有一个新方法
```C#
// CollectionDeckBoxVisual
// Token: 0x06000F2D RID: 3885 RVA: 0x00054CB7 File Offset: 0x00052EB7
public FormatType GetFormatType()
{
	return this.m_formatType;
}
```

**Comment by chucklu** [comment]
```C#
// Triton.Game.Mapping.CollectionDeckBoxVisual
// Token: 0x06009C16 RID: 39958
public FormatType get_FormatType()
{
	return base.method_11<FormatType>("GetFormatType", Array.Empty<object>());
}
// Triton.Game.Mapping.CollectionDeckBoxVisual
// Token: 0x170013AC RID: 5036
// (get) Token: 0x06003D59 RID: 15705
public bool m_isWild
{
	get
	{
		return this.get_FormatType() == FormatType.FT_WILD;
	}
}
```
