### ISSUE TITLE
Options.GetBool(Option option) Process must have frozen or gotten out of sync

### ISSUE THREAD

**Issue by chucklu** [ChuckHearthstone/SilverFish#56]
2021-04-17 18:16:58.776+08:00 - [Tick] Exception during execution:
Buddy.Coroutines.CoroutineUnhandledException: Exception was thrown by coroutine ---> GreyMagic.InjectionDesyncException: Process must have frozen or gotten out of sync: Injection Finished Event was never fired
   at GreyMagic.Executor.WaitForInjection(Int32 timeout)
   at GreyMagic.Executor.SharedExecuteLogicEnd(Int32 timeout)
   at GreyMagic.Executor.Execute(Int32 timeout)
   at GreyMagic.ExternalProcessMemory.CallInjected[T](IntPtr address, CallingConvention callingConvention, Object[] args)
   at ns27.Class276.method_43(IntPtr intptr_37, IntPtr intptr_38, Object[] object_0)
   at Triton.Game.Mono.MonoClass.method_7(String string_4, Enum20[] enum20_0, Object[] object_0)
   at Triton.Game.Mono.MonoClass.method_10[T](String string_4, Enum20[] enum20_0, Object[] object_0)
   at Triton.Game.Mapping.Options.GetBool(Option option)
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Struct88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Struct87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Struct60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Buddy.Coroutines.Coroutine.Class66.Struct18.MoveNext()
   --- End of inner exception stack trace ---
   at Buddy.Coroutines.Coroutine.method_2(Boolean bool_2)
   at Buddy.Coroutines.Coroutine.method_0(Boolean bool_2)
   at Buddy.Coroutines.Coroutine.Resume()
   at Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Tick()
   at Triton.Bot.BotManager.smethod_1(IBot ibot_1)

**Comment by chucklu** [comment]
After fixed Options.GetBool(Option option), the process just exit when click play button

> 2021-04-18 15:47:17.244+08:00 [15] INFO  Triton.Common.LogUtilities.Logger - [HubScene] Now clicking on the "Play" button.
> 2021-04-18 15:47:17.935+08:00 [15] INFO  Triton.Common.LogUtilities.Logger - [IsClientInUsableState] SceneMgr.IsTransitioning.
> 2021-04-18 15:47:18.897+08:00 [15] INFO  Triton.Common.LogUtilities.Logger - [IsClientInUsableState] !SceneMgr.IsSceneLoaded.
> 2021-04-18 15:47:21.464+08:00 [15] INFO  Triton.Common.LogUtilities.Logger - [IsClientInUsableState] !SceneMgr.IsSceneLoaded.
> 2021-04-18 15:47:22.838+08:00 [15] INFO  Triton.Common.LogUtilities.Logger - [IsClientInUsableState] !SceneMgr.IsSceneLoaded.
> 2021-04-18 15:47:23.704+08:00 [15] INFO  Triton.Common.LogUtilities.Logger - [IsClientInUsableState] SceneMgr.IsTransitioning.
> 2021-04-18 15:47:24.518+08:00 [15] INFO  Triton.Common.LogUtilities.Logger - [IsClientInUsableState] Box.IsBusy.
> 2021-04-18 15:47:25.394+08:00 [15] INFO  Triton.Common.LogUtilities.Logger - [TournamentScene]
> 2021-04-18 15:47:33.157+08:00 [31] INFO  Triton.Common.LogUtilities.Logger - [ProcessExited] The game process has closed. Hearthbuddy will now close.
